### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Priderino** [theishiopian/ForageCraft#53]
It would be nice to have a config to modify the rock/sticks spawn rate and its drops. And maybe even control the spawn rates by biomes. Also a config do disable leeks.

**Comment by JTBlum** [comment]
I would be extremely happy to see the config option for leeks. There's already a config option to disable rocks in the file system, but it doesn't seem to work and an in-game config is always preferable to editing the file system.

**Comment by theishiopian** [comment]
The config doesnt work? Hm, I'll need to take a look at that once school gets out. As for the leeks, I assume you don't like them because of the rather shitty texture?

**Comment by JonathanTheInsane** [comment]
I’ll look at the configuration classes once I feel less sick

**Comment by theishiopian** [comment]
If you could open an issue, I'll assign jonathan. Both of us are unfortunately unavailable for a while (calculus is harder than it looks).

**Comment by JTBlum** [comment]
Actually I don't like them because they don't fit with the theme and scope of the mod as described, and they don't integrate with other mods that I use like Harvestcraft. Adding leeks and other foods to the game is just fine, but I thought the mission statement as it were was to add things that made sense without going too far from vanilla game play. It's kind of the same issue as the scarecrow without crows.

**Comment by theishiopian** [comment]
Crows are on their way. As for scope, I pretty much add whatever I want. I wont give an option to disable something just because its "out of scope", but I am willing to attempt better inter-mod integration.

**Comment by JTBlum** [comment]
Fair enough. It's not my mod, after all. I'd still like to see it (a config option for leeks), but that's just a request. A well-configured/configurable mod can be enjoyed by more people, in my opinion. And I like the idea of the crows as a way to counter-balance any potential over-abundance of seeds generated by breaking grass blocks and such. They would/will also add a little more flavor and interactivity to the game, which is always nice.

Since I'm doing suggestions as per the thread title, I would also like to see them added to whatever group allows you to lure and feed them to chickens and get the "seedy place" achievement.

**Comment by theishiopian** [comment]
I think that I can make chickens like seeds. Tell you what: lets leave this thread open for now, as a place for people to post suggestions. We can get a better place later.

**Comment by JTBlum** [comment]
I would appreciate the seed/chicken change. It would make leek seeds more useful even if someone had/has a problem with them as a crop.

**Comment by theishiopian** [comment]
I do appreciate the input. I'm unfortunately also indisposed, as the combination of game development at school and calculus class is kinda kicking my ass. With any luck the tow of us will be back within a week or so.

**Comment by JTBlum** [comment]
I understand. Calc 2 was hellish, and while I really enjoyed it calc 1 wasn't any easier.

**Comment by DrakoAlcarus** [comment]
I got one I want for my pack: A stone chisel/hatchet made from 1-2 flat rock and 1 stick. Just a simple little tool that has 8 uses. I want to start my pack off simply without tree punching, but get a crafting table. Not a fan of primal tech, so anyway to make early game a bit more vanilla works.

**Comment by DrakoAlcarus** [comment]
Also, can we get an option to remove leeks or tweak saturation? It's a little OP.

**Comment by DrakoAlcarus** [comment]
You ever plan to allow chickens to eat the seeds and/or have a config option to disable seeds?
